version: "3.9"

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx_webserver_for_wordpress.conf:/etc/nginx/nginx.conf
      - ./wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - internal_network

  php-fpm:
    image: php:8-fpm
    container_name: php_fpm_container
    restart: always
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - internal_network

  wordpress:
    image: wordpress:latest
    restart: always
    container_name: wordpress_container
    networks:
      - internal_network
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - ./wordpress_data:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb_container
    networks:
      - internal_network
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - ./mariadb_data:/var/lib/mysql

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    container_name: cloduflare_tunnel_container
    volumes:
      - ./cloudflare_configuration_files:/etc/cloudflare
    networks:
      - internal_network
    command: tunnel --no-autoupdate run
    env_file:
      - cloudflare_token.env

volumes:
  wordpress_data:
  mariadb_data:

networks:
  internal_network:
    driver: bridge
